# Generated by Django 4.2 on 2025-09-25 16:01

from django.db import migrations, models


def populate_unit_price(apps, schema_editor):
    OrderLineItem = apps.get_model('checkout', 'OrderLineItem')
    for line_item in OrderLineItem.objects.select_related('product'):
        line_item.unit_price = line_item.product.price
        line_item.lineitem_total = line_item.unit_price * line_item.quantity
        line_item.save(update_fields=['unit_price', 'lineitem_total'])


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0008_alter_order_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_eta",
            field=models.DateField(
                blank=True,
                help_text="Estimated delivery date presented to customers.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional delivery instructions provided by the customer.",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_message",
            field=models.CharField(
                blank=True,
                help_text="Human friendly status message shown on confirmation page.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("awaiting", "Awaiting Payment"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="awaiting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_unit_price, migrations.RunPython.noop),
    ]
