# Generated by Django 4.2 on 2025-09-25 16:01

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options"),
    ]

    def generate_category_slugs(apps, schema_editor):
        Category = apps.get_model('products', 'Category')
        for category in Category.objects.all():
            base_slug = slugify(category.friendly_name or category.name)
            slug = base_slug
            suffix = 1
            while Category.objects.filter(slug=slug).exclude(pk=category.pk).exists():
                suffix += 1
                slug = f"{base_slug}-{suffix}"
            category.slug = slug
            category.save(update_fields=['slug'])

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description shown on category landing pages.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first in navigation menus."
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon class to visually represent the category.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Used in URLs. Automatically generated from the name if left blank.",
                max_length=210,
                unique=True,
            ),
        ),
        migrations.RunPython(generate_category_slugs, migrations.RunPython.noop),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Optional brand or maker shown on listings.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="inventory_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Current sellable stock for physical items."
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive products are hidden from the shop front.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(
                default=False,
                help_text="Digital goods ignore stock tracking and always remain in stock.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Show a warning badge when stock is at or below this value.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Used on product listings and marketing widgets.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True, help_text="Used to fine tune delivery estimates.", null=True
            ),
        ),
    ]
